services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    networks:
      - todo_app_network

  database:
    build: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_app_network

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DB_HOST: database
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5001:5001"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - todo_app_network

volumes:
  postgres_data:

networks:
  todo_app_network:
    driver: bridge